# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_status_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
