# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_last_status_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
