# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 12:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='raw',
        ),
    ]
